In [200]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

np.random.seed(42)
n, m = 5, 3
A = np.random.randn(n, m)

print("Macierz A (5x3):")
print(A)

Macierz A (5x3):
[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783]]


In [201]:
AAT = A @ A.T
print("Macierz AAT = A * A^T:")
print(AAT)

Macierz AAT = A * A^T:
[[ 0.68534241  0.63723771  0.37423535  0.03192355 -0.73248507]
 [ 0.63723771  2.42926786  2.33541214  1.04389051  1.2203838 ]
 [ 0.37423535  2.33541214  3.30327538  0.71982313 -0.27640305]
 [ 0.03192355  1.04389051  0.71982313  0.72603156  1.82127253]
 [-0.73248507  1.2203838  -0.27640305  1.82127253  6.69452856]]


In [202]:
eigvals_U, eigvecs_U = np.linalg.eigh(AAT)

sorted_indices = np.argsort(eigvals_U)[::-1]
eigvals_U = eigvals_U[sorted_indices]
eigvals_U = np.clip(eigvals_U, a_min=0, a_max=None)
eigvecs_U = eigvecs_U[:, sorted_indices]


print("Wartości własne AAT (λ):")
print(eigvals_U)
print("----------")
print("Wektory własne AAT (macierz U):")
print(eigvecs_U)

Wartości własne AAT (λ):
[7.74157056e+00 5.30293744e+00 7.93937784e-01 4.62238613e-16
 0.00000000e+00]
----------
Wektory własne AAT (macierz U):
[[-0.05270272 -0.18963358 -0.77197309  0.52168995 -0.30521905]
 [ 0.32414502 -0.53173651 -0.38304421 -0.4070005   0.54755274]
 [ 0.15872023 -0.74082394  0.49925089  0.37862819 -0.18269378]
 [ 0.29366099 -0.09983215 -0.08377416 -0.57209682 -0.75464155]
 [ 0.88358561  0.35001259  0.03263609  0.30254933  0.06454792]]


In [203]:
S_diag = np.sqrt(eigvals_U)
S = np.zeros((n, m))
for i in range(min(n, m)):
    S[i, i] = S_diag[i]

print("Macierz S (diagonalna, Sii = sqrt(λi)):")
print(S)

Macierz S (diagonalna, Sii = sqrt(λi)):
[[2.7823678  0.         0.        ]
 [0.         2.30281077 0.        ]
 [0.         0.         0.89103186]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]


In [204]:
S_inv = np.zeros((m, m))
for i in range(min(n, m)):
    if S[i, i] != 0:
        S_inv[i, i] = 1 / S[i, i]

r = np.linalg.matrix_rank(A)
U_r = eigvecs_U[:, :r]
S_r = np.diag(np.sqrt(eigvals_U[:r]))
S_inv = np.linalg.inv(S_r)

V = (A.T @ U_r) @ S_inv

print("Macierz V (z V = Uᵗ A S⁻¹):")
print(V)
print("------------")
print("Macierz VT (wiersze wektorów własnych):")
print(V.T)

Macierz V (z V = Uᵗ A S⁻¹):
[[ 0.39221288 -0.88736689 -0.24238207]
 [-0.63738516 -0.45214951  0.62393989]
 [-0.66325653 -0.09022653 -0.74293334]]
------------
Macierz VT (wiersze wektorów własnych):
[[ 0.39221288 -0.63738516 -0.66325653]
 [-0.88736689 -0.45214951 -0.09022653]
 [-0.24238207  0.62393989 -0.74293334]]


In [205]:
ATA = A.T @ A
print("Macierz ATA = A^T * A:")
print(ATA)

eigvals_V, eigvecs_V = np.linalg.eigh(ATA)
sorted_indices = np.argsort(eigvals_V)[::-1]
eigvals_V = eigvals_V[sorted_indices]
eigvecs_V = eigvecs_V[:, sorted_indices]

print("Wartości własne ATA:")
print(eigvals_V)
print("----------------------")
print("Wektory własne ATA (macierz V):")
print(eigvecs_V)

Macierz ATA = A^T * A:
[[ 5.41317515  0.07226879 -1.44633287]
 [ 0.07226879  4.53829814  3.12105943]
 [-1.44633287  3.12105943  3.88697249]]
Wartości własne ATA:
[7.74157056 5.30293744 0.79393778]
----------------------
Wektory własne ATA (macierz V):
[[-0.39221288 -0.88736689 -0.24238207]
 [ 0.63738516 -0.45214951  0.62393989]
 [ 0.66325653 -0.09022653 -0.74293334]]


In [206]:
S_diag2 = np.sqrt(eigvals_V)
S2 = np.zeros((n, m))
for i in range(min(n, m)):
    S2[i, i] = S_diag2[i]

print("Macierz S (z λ ATA):")
print(S2)
print("----------------")
print("Macierz VT (wierszami):")
print(eigvecs_V.T)

Macierz S (z λ ATA):
[[2.7823678  0.         0.        ]
 [0.         2.30281077 0.        ]
 [0.         0.         0.89103186]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
----------------
Macierz VT (wierszami):
[[-0.39221288  0.63738516  0.66325653]
 [-0.88736689 -0.45214951 -0.09022653]
 [-0.24238207  0.62393989 -0.74293334]]


In [207]:
S_inv2 = np.zeros((m, m))
for i in range(min(n, m)):
    if S2[i, i] != 0:
        S_inv2[i, i] = 1 / S2[i, i]

U = A @ eigvecs_V @ S_inv2
print("Macierz U (z A·V·S⁻¹):")
print(U)

Macierz U (z A·V·S⁻¹):
[[ 0.05270272 -0.18963358 -0.77197309]
 [-0.32414502 -0.53173651 -0.38304421]
 [-0.15872023 -0.74082394  0.49925089]
 [-0.29366099 -0.09983215 -0.08377416]
 [-0.88358561  0.35001259  0.03263609]]


In [210]:
r = np.linalg.matrix_rank(A)

U1 = U_r
S1 = S_r
V1 = V.T 

# to czyni true
# U1 = eigvecs_U
# V1 = V
# S1 = S

U2 = U
V2 = eigvecs_V
S2 = S2

print("Czy U z obu metod się zgadza:", np.allclose(np.abs(U1[:, :r]), np.abs(U2)))
print("Czy V z obu metod się zgadza:", np.allclose(np.abs(V1.T[:, :r]), np.abs(V2.T)))

Czy U z obu metod się zgadza: True
Czy V z obu metod się zgadza: False


In [211]:
A1 = U1 @ S1 @ V1
print("Czy A1 = U1 S1 V1ᵗ odtwarza A:", np.allclose(A, A1))

A2 = U2[:, :r] @ S2[:r, :r] @ V2[:r, :].T
print("Czy A2 = U2 S2 V2ᵗ odtwarza A:", np.allclose(A, A2))

Czy A1 = U1 S1 V1ᵗ odtwarza A: True
Czy A2 = U2 S2 V2ᵗ odtwarza A: True


In [212]:
from scipy.linalg import subspace_angles

angles = subspace_angles(V1.T[:, :r], V2[:, :r])
print("Kąty między przestrzeniami wyznaczonymi przez V:", angles)

Kąty między przestrzeniami wyznaczonymi przez V: [2.33809455e-16 1.80512056e-16 1.97581847e-17]


In [190]:
S_diag = np.sqrt(np.clip(eigvals_V, 0, None))
rank_A = np.sum(S_diag > 1e-10)

dim_R = rank_A
dim_N = m - rank_A

print("dim R(A) =", dim_R)
print("dim N(A) =", dim_N)

dim R(A) = 3
dim N(A) = 0
