In [514]:
import numpy as np

# np.random.seed(42)
n, m = 3, 5
A = np.array([
    [3, 1],
    [2, 2],
    [0, 1]
])
n, m = A.shape
r = np.linalg.matrix_rank(A)

print("Macierz A (5x3):")
print(A)

Macierz A (5x3):
[[3 1]
 [2 2]
 [0 1]]


In [515]:
AAT = A @ A.T
print("Macierz AAT = A * A^T:")
print(AAT)

Macierz AAT = A * A^T:
[[10  8  1]
 [ 8  8  2]
 [ 1  2  1]]


In [516]:
eigvals_U, eigvecs_U = np.linalg.eigh(AAT)

sorted_indices = np.argsort(eigvals_U)[::-1]
eigvals_U = eigvals_U[sorted_indices]
eigvals_U = np.clip(eigvals_U, a_min=0, a_max=None)
eigvecs_U = eigvecs_U[:, sorted_indices]


print("Wartości własne AAT (λ):")
print(eigvals_U)
print("----------")
print("Wektory własne AAT (macierz U):")
print(eigvecs_U)

Wartości własne AAT (λ):
[1.73262379e+01 1.67376208e+00 3.70496235e-16]
----------
Wektory własne AAT (macierz U):
[[-0.73938702 -0.56158329  0.37139068]
 [-0.66132786  0.50229537 -0.55708601]
 [-0.12630238  0.65751317  0.74278135]]


In [517]:
S_diag = np.sqrt(eigvals_U)
S = np.zeros((n, m))
for i in range(min(n, m)):
    S[i, i] = S_diag[i]

print("Macierz S (diagonalna, Sii = sqrt(λi)):")
print(S)

Macierz S (diagonalna, Sii = sqrt(λi)):
[[4.16247978 0.        ]
 [0.         1.29373957]
 [0.         0.        ]]


In [519]:
S_inv = np.zeros((n, m))
for i in range(min(n, m)):
    if S[i, i] != 0:
        S_inv[i, i] = 1 / S[i, i]


# S_r = np.diag(np.sqrt(eigvals_U[:r]))
# S_inv = np.linalg.inv(S_r)

V = A.T @ eigvecs_U @ S_inv

print("Macierz VT (wiersze wektorów własnych):")
print(V.T)

Macierz VT (wiersze wektorów własnych):
[[-0.85065081 -0.52573111]
 [-0.52573111  0.85065081]]


In [520]:
ATA = A.T @ A
print("Macierz ATA = A^T * A:")
print(ATA)

eigvals_V, eigvecs_V = np.linalg.eigh(ATA)
eigvals_V = np.clip(eigvals_V, a_min=0, a_max=None)
sorted_indices = np.argsort(eigvals_V)[::-1]
eigvals_V = eigvals_V[sorted_indices]
eigvecs_V = eigvecs_V[:, sorted_indices]

print("--------------------")
print("Wartości własne ATA:")
print(eigvals_V)
print("----------------------")
print("Wektory własne ATA (macierz V):")
print(eigvecs_V)

Macierz ATA = A^T * A:
[[13  7]
 [ 7  6]]
--------------------
Wartości własne ATA:
[17.32623792  1.67376208]
----------------------
Wektory własne ATA (macierz V):
[[-0.85065081  0.52573111]
 [-0.52573111 -0.85065081]]


In [521]:
S_diag2 = np.sqrt(eigvals_V)
S2 = np.zeros((n, m))
for i in range(min(n, m)):
    S2[i, i] = S_diag2[i]

print("Macierz S (z λ ATA):")
print(S2)
print("----------------")
print("Macierz VT (wierszami):")
print(eigvecs_V.T)

Macierz S (z λ ATA):
[[4.16247978 0.        ]
 [0.         1.29373957]
 [0.         0.        ]]
----------------
Macierz VT (wierszami):
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [522]:
S_inv2 = np.zeros((n, m))
for i in range(min(n, m)):
    if S2[i, i] != 0:
        S_inv2[i, i] = 1 / S2[i, i]

U = A @ eigvecs_V @ S_inv2.T
print("Macierz U (z A·V·S⁻¹):")
print(U)

Macierz U (z A·V·S⁻¹):
[[-0.73938702  0.56158329  0.        ]
 [-0.66132786 -0.50229537  0.        ]
 [-0.12630238 -0.65751317  0.        ]]


In [523]:
U1 = eigvecs_U
V1 = V
S1 = S

U2 = U
V2 = eigvecs_V
S2 = S2

print("Czy U z obu metod się zgadza:", np.allclose(np.abs(U1[:, :r]), np.abs(U2[:, :r])))
print("Czy S z obu metod się zgadza:", np.allclose(np.abs(S1), np.abs(S2)))
print("Czy V z obu metod się zgadza:", np.allclose(np.abs(V1[:, :r]), np.abs(V2[:, :r])))

Czy U z obu metod się zgadza: True
Czy S z obu metod się zgadza: True
Czy V z obu metod się zgadza: True


In [524]:
A1 = U1 @ S1 @ V1.T
print("Czy A1 = U1 S1 V1ᵗ odtwarza A:", np.allclose(A, A1))

A2 = U2 @ S2 @ V2.T
print("Czy A2 = U2 S2 V2ᵗ odtwarza A:", np.allclose(A, A2))

Czy A1 = U1 S1 V1ᵗ odtwarza A: True
Czy A2 = U2 S2 V2ᵗ odtwarza A: True


In [526]:
A1

array([[3.0000000e+00, 1.0000000e+00],
       [2.0000000e+00, 2.0000000e+00],
       [5.6494128e-16, 1.0000000e+00]])

In [527]:
A2

array([[3.0000000e+00, 1.0000000e+00],
       [2.0000000e+00, 2.0000000e+00],
       [1.2127222e-17, 1.0000000e+00]])

In [530]:
S_diag = np.sqrt(np.clip(eigvals_V, 0, None))
rank_A = np.sum(S_diag > 1e-10)

dim_R = rank_A
dim_N = m - rank_A

print("dim R(A) =", dim_R)
print("dim N(A) =", dim_N)

dim R(A) = 2
dim N(A) = 0
